# Leave server-uuid blank to generate a new one. Once it's been set, do not change it, or users will be able to verify a second time.
server-uuid: ""
orb-group-name: "orb-humans"
# If you want to require Orb verification, leave device-group-name blank.
device-group-name: "device-humans"
web-url: "https://minecraft.worldcoin.org"

# Messages with Hex colors. use with this format: <#FF6600> </#FF6600> or <&a> </&a>
# example using Hex Colors foo: <#FF6600>foo</#FF6600>
# example using Hex Color bar: <&a>bar</&a>
messages:
    verify-success: "&aYou've successfully verified with World ID!"
    verify-error: "&cError while verifying with World ID. Please try again."
    verify-failure: "&cYou have failed verification with World ID. Please try again."
    verify-already-verified: "&ePlayer is already verified with World ID."
    verify-level: "&4This Verification Level is not accepted."
    verify-invalid: "&4Invalid Verification Level."
    verify-click-here: "&f&lClick here to verify with World ID: &r"
    verify-now: "<#05F511>&lVerify me NOW!</#05F511>"

listener-messages:
    welcome-msg: "&aWelcome to the server now using WorldID!"
    verify-welcome-msg: "&aYou've been verified with World ID!"
    verify-to-msg: "&eYou haven't been verified with World ID!"
    verify-msg: "&bYou can get permissions by typing the `/verify` command to verify with World ID!"